# Generated by Django 3.2.24 on 2024-02-24 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='note',
        ),
    ]
