# Generated by Django 3.2.24 on 2024-03-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0004_profile_old_cart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shippingaddress',
            options={'verbose_name_plural': 'Shipping Address'},
        ),
    ]
